server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

spring:
  application:
    name: user-login-and-registration
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/registration
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# smtp setting are for https://github.com/maildev/maildev
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

